# Site settings
title: Blog of wzbozz
email: something@example.com
description: > # this means to ignore newlines until "baseurl:"
  description here.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wzbozz.github.io" # the base hostname & protocol for your site
github_username: wzbozz 
#linkedin_url: "http://"
#facebook_url: "https://www.facebook.com/"
flickr_url: ""

imageurl: "https://wzbozz.github.io/images"

# Build settings
markdown: kramdown
kramdown:
        input: GFM
#highlighter: pygments
#highlighter: rouge

# _pages
include: ['_pages']
